#cloud-config

runcmd:
 - export ADMIN_USERNAME=${adminUsername}
 - export DB2_ADMIN_PASSWORD=${adminPassword}
 - export DB2_FENCED_PASSWORD=${adminPassword}
 - export INSTALLER_STORAGEACCOUNT_NAME=${installerStorageAccountName}
 - export INSTALLER_STORAGECONTAINER_NAME=${installerContainerName}
 - export INSTALLER_SAS_TOKEN=${installerSASToken}
 - export DB2_INSTALLER_ARCHIVE_FILENAME=
 - sudo yum -y install libstdc++.i686 libXmu.i686 libacl.i686 ncurses-libs.i686 ncurses-compat-libs.i686 motif.i686 xterm libmount.i686 libgcc.i686 libnsl.i686 libXdmcp.i686 libxcrypt.i686 libXdmcp libnsl psmisc elfutils-libelf-devel make
 - sudo yum -y install ksh mksh
 - sudo yum install -y java-1.8.0-openjdk
 - sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
 - sudo dnf install -y python3-dnf-plugin-versionlock
 - sudo wget https://aka.ms/downloadazcopy-v10-linux -O /tmp/azcopy.tar.gz
 - sudo tar -xvf /tmp/azcopy.tar.gz -C /tmp
 - sudo mv /tmp/azcopy_linux* /tmp/azcopy
 - sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
 - sudo parted /dev/sdc --script mklabel gpt mkpart xfspart xfs 0% 100%
 - sudo mkfs.xfs /dev/sdc1
 - sudo partprobe /dev/sdc1 
 - sudo mkdir /db2data
 - sudo mount /dev/sdc1 /mnt/db2data
 - FSTAB="$(blkid | grep sdc1 | awk '$0=$2' | sed 's/"//g')   /db2data   xfs   defaults,nofail   1   2"
 - sudo su -c "echo $FSTAB >> /etc/fstab"
 - sudo rm /mnt/install.rsp
 - sudo su db2inst1 -c "ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa"
 - sudo su - -c "ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa"
 - sudo chown -R ${adminUsername}:${adminUsername} /home/${adminUsername}/
 - exit
 - sudo firewall-cmd --permanent --zone=public --add-port=25000/tcp
 - sudo firewall-cmd --permanent --zone=public --add-port=25010/tcp
 - sudo firewall-cmd --permanent --zone=public --add-port=3121/tcp
 - sudo firewall-cmd --permanent --zone=public --add-port=5403/tcp
 - sudo firewall-cmd --permanent --zone=public --add-port=5404/udp
 - sudo firewall-cmd --permanent --zone=public --add-port=5405/udp
 - sudo firewall-cmd --permanent --zone=public --add-port=62500/tcp
 - sudo chown -R db2inst1:db2iadm1 /mnt/db2data/
 - [ wget, -nv, "https://raw.githubusercontent.com/Azure/sterling/${branchName}/config/installers/install-db2-from-storageaccount.sh", -O, /tmp/install-db2-from-storageaccount.sh ]
 - chmod +x /tmp/install-db2-from-storageaccount.sh
 - sudo -E /tmp/install-db2-from-storageaccount.sh