#cloud-config

runcmd:
 - echo "Setting environment variables..."
 - export OMS_NAMESPACE=${omsNamespace}
 - export ARO_CLUSTER=${aroName}
 - export WHICH_OMS=${whichOMS}
 - export BRANCH_NAME=${branchName}
 - export LOCATION=${location}
 - export ADMIN_PASSWORD=${adminPassword}
 - export IBM_ENTITLEMENT_KEY=${ibmEntitlementKey}
 - export ACR_NAME=${acrName}
 - mkdir ~/.azure/
 - echo '{"subscriptionId":"${subscriptionID}","clientId":"${clientID}","clientSecret":"${clientSecret}","tenantId":"${tenantID}","resourceGroup":"${resourceGroupName}"}' > ~/.azure/osServicePrincipal.json
 - echo "Running system update..."
 - sudo dnf update -y
 - echo "System update completed!"
 - echo "Getting latest configuration script..."
 - [ wget, -nv, "https://raw.githubusercontent.com/Azure/sterling/${branchName}/config/installers/configure-aro-and-requirements.sh", -O, /tmp/configure-aro-and-requirements.sh ]
 - chmod +x /tmp/configure-aro-and-requirements.sh
 - echo "Running configuration script..."
 - sudo -E /tmp/configure-aro-and-requirements.sh
 - echo "Getting pgsql tools/configuration script..."
 - [ wget, -nv, "https://raw.githubusercontent.com/Azure/sterling/${branchName}/config/installers/setup-pgsql-tools.sh", -O, /tmp/setup-pgsql-tools.sh ]
 - echo "Running pgsql installation script..."
 - sudo -E /tmp/setup-pgsql-tools.sh
 
 
 