apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-sterling-oms
  namespace: openshift-marketplace
spec:
  displayName: IBM Sterling OMS
  image: '$OMS_VERSION'
  publisher: IBM
  sourceType: grpc 
  updateStrategy:
    registryPoll:
      interval: 10m0s
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: oms-operator
  namespace: '$OMS_NAMESPACE'
spec:
  channel: "v1.0"
  installPlanApproval: Automatic
  name: '$OPERATOR_NAME'
  source: ibm-sterling-oms
  sourceNamespace: openshift-marketplace
  startingCSV: '$OPERATOR_CSV'