kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: active-mq-storage
  namespace: active-mq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: azurefiles-premium
  volumeMode: Filesystem