apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: $OMS_NAMESPACE
spec:
  selector:
    matchLabels:
      app: activemq
  replicas: 1
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:latest
          ports:
            - containerPort: 61616
              protocol: TCP
            - containerPort: 8161
              protocol: TCP
