apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-pvc
  namespace: oms
spec:
  storageClassName: azurefiles-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem