apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2-pv
spec:
  storageClassName: azurefiles-standard
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - actimeo=30
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  azureFile:
    secretNamespace: oms