apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
  namespace: oms
spec:
  selector:
    matchLabels:
      app: db2
  replicas: 1
  template:
    metadata:
      labels:
        app: db2
    spec:
      volumes:
        - name: db2-data
          persistentVolumeClaim:
            claimName: db2-pvc
      privileged: true
      containers:
        - name: db2
          image: docker.io/ibmcom/db2
          env:
            - name: LICENSE
              value: 'accept'
            - name: DB2INSTANCE
              value: db2inst1
            - name: DB2INST1_PASSWORD
              value: 'changemeplease123!'
            - name: DBNAME
              value: 'testdb'
            - name: BLU
              value: 'false'
            - name: ENABLE_ORACLE_COMPATIBILITY
              value: 'false'
            - name: UPDATEAVAIL
              value: 'NO'
            - name: TO_CREATE_SAMPLEDB
              value: 'true'
            - name: REPODB
              value: 'true'
            - name: IS_OSXFS
              value: 'false'
            - name: PERSISTENT_HOME
              value: 'false'
            - name: HADR_ENABLED
              value: 'false'
          ports:
            - containerPort: 50000
          volumeMounts:
            - mountPath: '/database'
              name: db2-data
