apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: db2ucluster-db2dev1
spec:
  account:
    imagePullSecrets:
     - ibm-registry
    privileged: true
  environment:
    dbType: db2oltp
    instance:
      password: db2oltp
    ldap:
      enabled: false
  podConfig:
    db2u:
      resource:
        db2u:
          limits:
            cpu: '0.5'
            memory: 2Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
  addOns:
    rest:
     enabled: true
    graph:
     enabled: false
 
  size: 1
  version: 11.5.5.0-cn2
  storage:
    - name: meta
      type: "create"
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
    - name: data
      type: "create"
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Gi