apiVersion: v1
kind: Secret
metadata:
   name: '$NAMESPACE-oms-secret'
type: Opaque
stringData:
  consoleadminpassword: '$CONSOLEADMINPW'
  consolenonadminpassword: '$CONSOLENONADMINPW'
  dbpassword: '$DBPASSWORD'
  tlskeystorepassword: '$TLSSTOREPW'
  trustStorePassword: '$TRUSTSTOREPW'
  keyStorePassword: '$KEYSTOREPW'