license: accept
queueManager:
  nativeha:
    enable: true
    tls:
      secretName: helmsecure
  mqscConfigMaps:
    - name: helmsecure
      items:
        - mq.mqsc
  qminiConfigMaps:
    - name: helmsecure
      items:
        - mq.ini
  name: omsmq
persistence:
  dataPVC:
    enable: true
    storageClassName: azurefile-csi-premium
  logPVC:
    enable: true
    storageClassName: azurefile-csi-premium
  qmPVC:
    enable: true
    storageClassName: azurefile-csi-premium
security:
  context:
    fsGroup: 0
metadata:
  annotations:
    productName: "IBM MQ Advanced for Developers"
    productID: "2f886a3eefbe4ccb89b2adb97c78b9cb"
    productChargedContainers: ""
    productMetric: "FREE"
route:
  nodePort:
    webconsole: true
    mqtraffic: true
  loadBalancer:
    webconsole: true
    mqtraffic: true