apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: $clusterInstanceName
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: oms-machineset-z$zone
  namespace: openshift-machine-api
spec:
  replicas: $numReplicas
  selector:
    matchLabels:
      components: oms-machineset
      machine.openshift.io/cluster-api-cluster: $clusterInstanceName
      machine.openshift.io/cluster-api-machineset: $clusterInstanceName-oms-machineset-z$zone
  template:
    metadata:
      creationTimestamp: null
      labels:
        components: oms-machineset
        machine.openshift.io/cluster-api-cluster: $clusterInstanceName
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: $clusterInstanceName-oms-machineset-z$zone
    spec:
      metadata:
        creationTimestamp: null
        labels:
          components: oms-machineset
          node-role.kubernetes.io/worker: ""
          icp4data: oms-machineset2wh
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/$clusterInstanceName-$domain/providers/Microsoft.Compute/images/$clusterInstanceName
            sku: ""
            version: ""
          internalLoadBalancer: ""
          kind: AzureMachineProviderSpec
          location: $deployRegion
          managedIdentity: $clusterInstanceName-identity
          metadata:
            creationTimestamp: null
          natRule: null
          networkResourceGroup: $resourceGroupName
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: $aroilbname
          resourceGroup: $clusterInstanceName-$domainName
          subnet: $subnetWorkerNodeName
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D16_v3
          vnet: $vnetName
          zone: "$zone"